import Head from "next/head";
import Link from "next/link";
import { Button } from "../../ui/components/button";
import { ModeToggle } from "../../ui/components/modetoggle";
import { Input } from "../../ui/components/input";
import { Separator } from "../../ui/components/separator"
import {
  Card,
  CardTitle,
  CardHeader,
  CardDescription,
  CardContent,
  CardFooter,
} from "../../ui/components/card";
import { Icons } from "../../ui/icons"
import { api } from "~/utils/api";

export default function Login() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ModeToggle />
      <main className="bg-background flex justify-center items-center min-h-screen">
        <Card className="w-80 lg:w-90 bg-card rounded-lg shadow-lg">

          <CardHeader>
            <CardTitle>Login</CardTitle>
            <CardDescription>Don&#39;t have an account yet? <Link href={"../auth/Register"} className="link text-primary">Register</Link></CardDescription>
          </CardHeader>

          <CardContent>
            <div className="w-full flex justify-center space-x-4">
              <Button className="w-full flex items-center" variant="outline" type="button">
                <Icons.gitHub className="mr-2 h-4 w-4" />
                Github
              </Button>

              <Button className="w-full flex items-center" variant="outline" type="button">
                <Icons.google className="mr-2 h-4 w-4" />
                Google
              </Button>
            </div>

            <Separator/>

            <div>
              <p className="font-semibold mb-1">Email</p>
              <Input type="email" placeholder="" />
            </div>
            <div>
              <p className="font-semibold mb-1">Password</p>
              <Input type="password" placeholder="" />
            </div>

          </CardContent>
          <CardFooter className="flex flex-col items-end">
            <Button className="w-full mb-2" type="submit" >Login</Button>
            <Link className="link mb-4" href="">Forgot password?</Link>
            <Separator className="mb-2"/>

            <p className="description px-8 text-center text-sm text-muted-foreground">
              By clicking continue, you agree to our {" "}
              <Link href="" className="underline underline-offset-4 hover:text-primary">Terms of Service</Link>
              {" "} and {" "}
              <Link href="" className="underline underline-offset-4 hover:text-primary">Privacy Policy</Link>.
            </p>

          </CardFooter>
        </Card>
      </main>
    </>
  );
}
