import Head from "next/head";
import Link from "next/link"; // Import Link from Next.js
import { useState } from "react";
import { Button } from "../ui/components/button";
import { ModeToggle } from "../ui/components/modetoggle";
import { Input } from "../ui/components/input";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../ui/components/card";
import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ModeToggle />
      <main className="bg-background flex justify-center items-center min-h-screen">
        <Card className="w-80 lg:w-90 bg-card rounded-lg shadow-lg">
          <CardHeader>
            <CardTitle>
              Selection
            </CardTitle>
          </CardHeader>
          <CardContent>
            {/* Use Link component for navigation */}
            <Link href="/auth/login">
                <Button className="w-full mb-2" type="submit">
                  Login
                </Button>
            </Link>
            <Link href="/auth/register">
                <Button className="w-full mb-2" type="submit">
                  Register
                </Button>
            </Link>
          </CardContent>
        </Card>
      </main>
    </>
  );
}
