import Head from "next/head";
import Link from "next/link";
import { Button } from "../components/ui/button"
import { ModeToggle } from "../components/ui/modetoggle"
import { Input } from "../components/ui/input"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "../components/ui/card"

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ModeToggle/>
      <main className="bg-background flex justify-center items-center min-h-screen">
        <Card className="sm:w-fit md:w-80 lg:w-96 bg-card rounded-lg shadow-lg">
          <CardHeader>
            <CardTitle>Login</CardTitle>
          </CardHeader>
          <CardContent>
              <Input type="email" placeholder="Email" />
              <Input type="password" placeholder="Password" />
          </CardContent>
          <CardFooter>
            <Button type="submit" className="w-full">Login</Button>
          </CardFooter>
        </Card>
      </main>
    </>
  );
}
